# Liquid-Dockerfile for: Oracle-Java-8  and Eclipse at once
#
# ...usePrep___: none
# ...useBuild__: see script build.sh
# ...useRun____: see script run.sh
# ...see base__: https://github.com/fgrehm/docker-eclipse

# Pull Os-Base image.
FROM ubuntu:16.04


RUN sed 's/main$/main universe/' -i /etc/apt/sources.list && \
    apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer libxext-dev libxrender-dev libxtst-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

# Install libgtk as a separate step so that we can share the layer above with
# the netbeans image
RUN apt-get update && apt-get install -y libgtk2.0-0 libcanberra-gtk-module

#...use "-q"  at end of command to load data in quiete mode 
RUN wget http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/<ECLIPSE-RELEASE> -O /tmp/eclipse.tar.gz && \
    echo 'Installing eclipse' && \
    tar -xf /tmp/eclipse.tar.gz -C /opt && \
    rm /tmp/eclipse.tar.gz

# install maven
RUN wget http://www-eu.apache.org/dist/maven/maven-3/<MAVEN-RELEASE>/binaries/apache-maven-<MAVEN-RELEASE>-bin.tar.gz  -O /tmp/maven.tar.gz && \
   echo 'Installing maven ' && \
   tar -xf /tmp/maven.tar.gz -C /opt && \
   mv /opt/apache-maven-<MAVEN-RELEASE> /opt/maven && \
   rm -f /tmp/maven.tar.gz

RUN useradd -ms /bin/bash <CURRENT-USER> && \
    usermod -aG sudo <CURRENT-USER>

USER <CURRENT-USER>
ENV HOME /home/<CURRENT-USER>
WORKDIR /home/<CURRENT-USER>

CMD /opt/eclipse/eclipse
